spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://postgres:5432/${spring.application.name}
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.master-changelog.xml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: booking-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages:
    listener:
      additional:
        group-id: booking-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
  template:
    default-topic: booking-response
  logging:
    level:
      root: DEBUG
      org.springframework.kafka: DEBUG
      org.apache.kafka: DEBUG
