spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/${spring.application.name}
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.master-changelog.xml
  kafka:
    listener:
      concurrency: 3
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Используем JsonDeserializer для объектов
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  logging:
    level:
      root: DEBUG
      org.springframework.kafka: DEBUG
      org.apache.kafka: DEBUG